name: go

on:
  push:
    branches:
      - main

jobs:

  server-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run-cli
        working-directory: ./backend
        run: make dev-cli
